### PR TITLE
Allow client protocol version to be set in options

### PR DESCRIPTION
**Pull request by sshort**

### CODE REVIEW

**Comment by emersion** [comment]
I'd rather not make this configurable. The library should do the right thing automatically.

**Comment by sshort** [comment]
> I'd rather not make this configurable. The library should do the right thing automatically.

It's in the options - it does not work as is

**Comment by emersion** [comment]
"should do" as in "should be fixed to correctly do"

**Comment by sshort** [comment]
Fixes https://github.com/emersion/go-milter/issues/16

**Comment by sshort** [comment]
What do you think the fix is?  At the moment the library contains a client and a server that do not work together.

**Comment by sshort** [comment]
Can we set the client protocol version to 2 until the v6 changes have been implemented?

**Comment by emersion** [comment]
No. The client should figure out that the server supports only v2, and downgrade its own version automatically under the hood.

**Comment by sshort** [comment]
This should not have been commited in this state, should it?

**Comment by emersion** [comment]
Ideally, software shouldn't have bugs. It turns out software often has bugs.

**Comment by sshort** [comment]
"Doesn't work at all" seems like more than a bug :)

I'm thinking about whether to use our own fork until the protocol fallback is implemented.  I'd like to fix this properly, but I am not a milter expert.

**Comment by sshort** [comment]
Will have a go at the protocol fallback in the client.

**Pull request closed without merging**
