### PR TITLE
Fix/workaround change client protocol to 2

### PR DESCRIPTION
**Pull request by sshort**

### CODE REVIEW

**Comment by emersion** [comment]
NACK, this is a workaround rather than a proper fix.

**Comment by emersion** [comment]
Also we already have CI.

**Comment by sshort** [comment]
Sorry - for some reason github defaults the base repo to yours - I've switched this to my fork until this is fixed properly

**Comment by emersion** [comment]
Just to make things clear: don't expect this to be fixed overnight -- I review PRs on my free time, but I don't have any intention to work on this.

**Comment by sshort** [comment]
No worries - thats' why we've forked it.  I hope we can contribute to this - but don't have time right now.

**Comment by sshort** [comment]
Would this approach work for you?  Simply masking out the protocol flags when v2 is detected.

https://github.com/sshort/go-milter/pull/3

**Comment by emersion** [comment]
Hm maybe… I wonder if we need to do anything else and if clients are prepared for this… cc @foxcpp

**Pull request closed without merging**
